# Generated by Django 3.2.6 on 2021-09-03 07:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
